version: '3.8'
services:
  posture:
    image: paidax/posture:0.0.5
    container_name: posture
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - 10056:10056
    command: uvicorn main:app --port 10056 --host 0.0.0.0
